after_script:
  - docker images

before_script:
  - IMAGE="monero:${VERSION/\//-}"

env:
  - VERSION=0.15.0.1

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Monero"

services: docker
